config/routes.rb
Rails.application.routes.draw do
 resources :users do 
   member do 
    get :following
    get :followers 
   end 
 end 
 resources :microposts, only: [:create, :destroy]  
 resources :sessions, only: [:new, :create, :destroy]
 resources :relationships, only: [:create, :destroy]
 root 'static_pages#home' 
  get 'signup', to: 'users#new' 
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help' 
  get '/contact', to: 'static_pages#contact'

 

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in? 
      @micropost  = current_user.microposts.build 
      @feed_items = current_user.feed.paginate(page: params[:page])
       end
     end 

  def about
  end

  def help
  end

  def contact
  end 

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>We Help Students Find The Books They Need </h1>
<p> Our store specializes in helping studing find the right books <p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1> Contact Us For More Information </h1>
<p> Please contact us at sample@gmail.com </p>

app/views/static_pages/help.html.erb
<% provide(:title,"Help") %>
<h1> Need Help Selecting the Right Book ?</h1>
<p> Please let us know if we can assist you in any way. </p>

app/views/static_pages/home.html.erb
<!DOCTYPE html>
    <body>
        <div class="page-wrapper">
            <section class="header-10-sub v-center bg-midnight-blue">
                <div class="background">
                    &nbsp;
                </div>
                <div>
                    <div class="container">
                        <div class="hero-unit">
                            <h1>Freelancelot creative thinking community!</h1>
                              <p>
                                We already found them all so you don't have to  
                                <br/>
                                Were pretty good at it, try us out
                            </p>
                        </div>
                        <p class="lead">Click here to Sign in or Sign up</p>
                        <p class="lead">
                           <%=link_to "Sign up", signup_path, class: "btn btn-default btn-lg btn-clear" %>
                           <%=link_to "Sign in", signin_path, class: "btn btn-default btn-lg btn-clear" %>
                        </p>
                      </p>
                    </div>
                </div>
                <a class="control-btn " href="#"><span class="glyphicon glyphicon-arrow-down"></span></a>
            </section>
            <!-- logos -->
            <section class="logos">
                <div class="container">
                    <div><%= image_tag("mashable.png") %></div>
                    <div><%= image_tag("guardian.png") %></div>
                    <div><%= image_tag("forbes.png") %></div>
                    <div><%= image_tag("red-bull.png") %></div>                  
                    <div><%= image_tag("ny-times.png") %></div>
                </div>

            <!-- content-7  -->
            <section class="content-7 v-center">
                <div>

                    <div class="container">
                        <h3>Take a look at our awesome product</h3>

                        <div class="row v-center">
                            <div class="col-sm-3">
                                <div>
                                    Of course we haven’t forgotten about the responsive layout. Create a website with full mobile
                                    support.
                                </div>
                            </div>
                            <div class="col-sm-4">
                                <div class="col-sm-offset-1">
                                    <div class="screen-wrapper">
                                        <div class="screen">
                                            <%= image_tag("screen-popup.png", :alt => "screen popup") %>
                                            <%= image_tag("screen.png", :alt => "screen") %>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div class="col-sm-offset-2">
                                    <h6>Responsive Layout</h6>
                                    Of course we haven’t forgotten about the responsive layout. Full mobile support.
                                    <h6>Retina Ready</h6>
                                    Startup Framework works fine on devices supporting Retina Display. Feel the clarity!
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <!-- content-23  -->
            <section class="content-23 v-center bg-midnight-blue custom-bg">
                <div>
                    <div class="container">
                        <div class="hero-unit hero-unit-bordered">
                            <h1>Thinking Creative</h1>
                        </div>
                    </div>
                </div>
                <a class="control-btn" href="#"><span class="glyphicon glyphicon-arrow-down"></span> </a>
            </section>

            <!-- content-8  -->
            <section class="content-8 v-center">
                <div>
                    <div class="container">
                        <%= image_tag("art.jpg", width: '397', height: '193', class: "img-rounded") %>

                        <h3>We'll do all the dirty work so you dont have too!</h3>

                        <div class="row">
                            <div class="col-sm-6 col-sm-offset-3">
                                <p>We have a great surprise for Designmodo fans – our first free HTML user interface kit.
                                    Flat UI Free is made on the basis of Twitter Bootstrap in a stunning flat-style.
                                </p>
                                <a class="btn btn-large btn-clear" href="#">TRY IT NOW</a>
                            </div>
                        </div>
                    </div>
                </div>
            </section>

            <!-- content-11  -->
            <section class="content-11">
                <div class="container">
                    <span>You have the design, you have the code</span>
                    <a class="btn btn-large btn-danger" href="#">TRY IT NOW</a>
                </div>
            </section>

      
    </body>
</html>