config/routes.rb
Rails.application.routes.draw do
 resources :users do 
   member do 
    get :following
    get :followers 
   end 
 end 
 resources :microposts, only: [:create, :destroy]  
 resources :sessions, only: [:new, :create, :destroy]
 resources :relationships, only: [:create, :destroy]
 root 'static_pages#home' 
  get 'signup', to: 'users#new' 
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get '/about', to: 'static_pages#about'
  get '/help', to: 'static_pages#help' 
  get '/contact', to: 'static_pages#contact'

 

end

app/views/layouts/_footer.html.erb
  <!-- footer-3 -->
            <footer class="footer-3">
                <div class="container">
                    <div class="row v-center">
                        <div class="col-sm-2">
                            <a class="brand" href="#">Freelancelot</a>
                        </div>
                        <div class="col-sm-7">
                            <div class="additional-links">
                                Be sure to take a look to our <a href="#">Terms of Use</a> and <a href="#">Privacy Policy</a>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <h6>Shanghai, China</h6>
                            <div class="address">
                                West Nanjing Road, Suite 302<br>Shanghai, China, 90320
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </div>

app/views/layouts/_header.html.erb
        
     <!-- header-10 -->
            <header class="header-10">
                <div class="container">
                    <div class="navbar col-sm-12" role="navigation">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle"></button>
                            <a class="brand" href="#">Freelancelot</a>
                         </div>
                        <div class="collapse navbar-collapse pull-right">
                            <ul class="nav pull-left">
                               <li><%= link_to "About", about_path %></li>
                                 <% if signed_in? %>
                                 <li><%= link_to "Users", users_path %></li>
                                 <li><%= link_to "Job Posts", root_path %></li>
                                 <li class="dropdown">
                            <a href="" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
                        <ul class="dropdown-menu dropdown-menu-right">
                    <li><%= link_to "Profile", current_user %></li>
                    <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Sign out", signout_path, method: "delete" %></li>
                  </ul>
                </li>
             <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
            <li><%= link_to "Home", root_path %> 
          <% end %>
                               
                            </ul>
                        </div>
                    </div>
                </div>
            </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "jquery", "application.js", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>